services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: docker/dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
         python create_admin_user.py &&
        python manage.py runserver 0.0.0.0:8000
      "
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/dockerfile
      args:
        - VITE_BASE_URL=http://localhost:8000
    networks:
      - backend-network
    ports:
      - "3000:80"

volumes:
  postgres_data:
    driver: local

networks:
  backend-network:
    driver: bridge
