# Generated by Django 5.2.1 on 2025-08-09 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'Notificación In-App')], max_length=20)),
                ('trigger_event', models.CharField(choices=[('order_created', 'Orden Creada'), ('order_confirmed', 'Orden Confirmada'), ('order_shipped', 'Orden Enviada'), ('order_delivered', 'Orden Entregada'), ('order_cancelled', 'Orden Cancelada'), ('payment_successful', 'Pago Exitoso'), ('payment_failed', 'Pago Fallido'), ('cart_abandoned', 'Carrito Abandonado'), ('welcome', 'Bienvenida'), ('password_reset', 'Reset de Contraseña'), ('email_verification', 'Verificación de Email'), ('low_stock', 'Stock Bajo'), ('promotion_available', 'Promoción Disponible')], db_index=True, max_length=30)),
                ('subject', models.CharField(blank=True, help_text='Asunto (para emails) o título (para push notifications)', max_length=255, null=True)),
                ('content_html', models.TextField(blank=True, help_text='Contenido HTML (para emails)', null=True)),
                ('content_text', models.TextField(help_text='Contenido de texto plano')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['trigger_event', 'template_type', 'is_active'], name='notificatio_trigger_313bb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rendered_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('rendered_content_html', models.TextField(blank=True, null=True)),
                ('rendered_content_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora programada para el envío')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('order_notifications', models.BooleanField(default=True)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('shipping_notifications', models.BooleanField(default=True)),
                ('promotion_notifications', models.BooleanField(default=True)),
                ('marketing_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('provider_used', models.CharField(blank=True, help_text='Proveedor utilizado (SMTP, SendGrid, Twilio, etc.)', max_length=100, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationqueue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_queue', 'attempt_number'], name='notificatio_notific_cb901e_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_103f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['recipient_user', 'status'], name='notificatio_recipie_b509d6_idx'),
        ),
    ]
