# Generated by Django 5.1.7 on 2025-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'client'), (1, 'admin'), (2, 'superadmin')], default='0'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
