# Generated by Django 5.2.1 on 2025-08-09 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_productattribute_attribute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('abandoned', 'Abandonado'), ('converted', 'Convertido'), ('expired', 'Expirado')], db_index=True, default='active', max_length=20)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartAbandonmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email para enviar recordatorios', max_length=254)),
                ('abandonment_stage', models.CharField(choices=[('added_items', 'Items Agregados'), ('checkout_started', 'Checkout Iniciado'), ('payment_failed', 'Pago Fallido')], default='added_items', max_length=20)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('reminder_sent_count', models.PositiveIntegerField(default=0)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, help_text='Fecha en que se completó la compra', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abandonment_tracking', to='carts.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio al momento de agregar al carrito', max_digits=12, null=True)),
                ('selected_attributes', models.JSONField(blank=True, help_text='Atributos seleccionados como color, talla, etc.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_attribute', models.ForeignKey(blank=True, help_text='Variante específica del producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_attributes', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mi Lista de Deseos', max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_attributes', models.JSONField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=2)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.wishlist')),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='carts_cart_user_id_f43479_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id'], name='carts_cart_session_846cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'expires_at'], name='carts_cart_status_8438a8_idx'),
        ),
        migrations.AddIndex(
            model_name='cartabandonmenttracking',
            index=models.Index(fields=['email', 'abandonment_stage'], name='carts_carta_email_f6ca70_idx'),
        ),
        migrations.AddIndex(
            model_name='cartabandonmenttracking',
            index=models.Index(fields=['last_activity_at'], name='carts_carta_last_ac_71493a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartabandonmenttracking',
            index=models.Index(fields=['recovered_at'], name='carts_carta_recover_07712d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='carts_carti_cart_id_8f3e40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'product_attribute')},
        ),
        migrations.AddIndex(
            model_name='recentlyviewed',
            index=models.Index(fields=['user', 'last_viewed_at'], name='carts_recen_user_id_71219d_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyviewed',
            index=models.Index(fields=['session_id', 'last_viewed_at'], name='carts_recen_session_86624f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewed',
            unique_together={('session_id', 'product'), ('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='savedforlater',
            index=models.Index(fields=['user', 'saved_at'], name='carts_saved_user_id_4fde65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedforlater',
            unique_together={('user', 'product', 'product_attribute')},
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user'], name='carts_wishl_user_id_45d079_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['is_public'], name='carts_wishl_is_publ_8ae53d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist', 'priority'], name='carts_wishl_wishlis_00256f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product', 'product_attribute')},
        ),
    ]
