# Generated by Django 5.2.1 on 2025-11-04 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_discount_amount_cart_shipping_cost_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Cupón de descuento aplicado al carrito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='promotions.coupon'),
        ),
    ]
