# Generated by Django 5.2.1 on 2025-08-09 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderitem_orderstatushistory_remove_cart_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('method_type', models.CharField(choices=[('standard', 'Envío Estándar'), ('express', 'Envío Express'), ('overnight', 'Envío Nocturno'), ('pickup', 'Retiro en Sucursal'), ('same_day', 'Envío el Mismo Día')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, help_text='Costo adicional por kilogramo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Peso mínimo en kg', max_digits=8, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Peso máximo en kg', max_digits=8, null=True)),
                ('estimated_days_min', models.PositiveIntegerField(default=1)),
                ('estimated_days_max', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('is_insured', models.BooleanField(default=False)),
                ('carrier_config', models.JSONField(blank=True, help_text='Configuración específica del transportista', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shipping_zone', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('countries', models.JSONField(default=list, help_text='Lista de países cubiertos por esta zona')),
                ('states_provinces', models.JSONField(default=list, help_text='Lista de provincias/estados cubiertos')),
                ('cities', models.JSONField(default=list, help_text='Lista de ciudades específicas (opcional)')),
                ('postal_codes', models.JSONField(default=list, help_text='Lista de códigos postales o rangos')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Dirección')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apartamento, suite, etc.')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state_province', models.CharField(max_length=100, verbose_name='Provincia/Estado')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('country', models.CharField(default='Argentina', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_type', models.CharField(choices=[('billing', 'Facturación'), ('shipping', 'Envío'), ('both', 'Ambos')], default='both', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instrucciones de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('carrier', models.CharField(blank=True, help_text='Transportista (Correo Argentino, OCA, Andreani, etc.)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('in_transit', 'En Tránsito'), ('out_for_delivery', 'En Reparto'), ('delivered', 'Entregado'), ('failed_delivery', 'Entrega Fallida'), ('returned', 'Devuelto'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=8, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Dimensiones del paquete: {length, width, height} en cm', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('recipient_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_to', models.CharField(blank=True, help_text='Persona que recibió el paquete', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.address')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='shipping_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='shipping.shippingzone'),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Envío Creado'), ('picked_up', 'Recogido'), ('in_transit', 'En Tránsito'), ('arrived_facility', 'Llegó a Instalación'), ('departed_facility', 'Salió de Instalación'), ('out_for_delivery', 'En Reparto'), ('delivered', 'Entregado'), ('delivery_attempted', 'Intento de Entrega'), ('returned_to_sender', 'Devuelto al Remitente'), ('exception', 'Excepción'), ('customs_clearance', 'Despacho Aduanero')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('event_datetime', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('carrier_event_code', models.CharField(blank=True, max_length=50, null=True)),
                ('carrier_raw_data', models.JSONField(blank=True, help_text='Datos completos del evento del transportista', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-event_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'address_type'], name='shipping_ad_user_id_c10144_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code', 'city'], name='shipping_ad_postal__30a86e_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipping_sh_trackin_af3d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'created_at'], name='shipping_sh_status_58d901_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['carrier', 'status'], name='shipping_sh_carrier_86be7d_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['is_active', 'display_order'], name='shipping_sh_is_acti_7cf301_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['method_type'], name='shipping_sh_method__aeb4eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingmethod',
            unique_together={('shipping_zone', 'code')},
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['shipment', 'event_datetime'], name='shipping_tr_shipmen_f4c34f_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['event_type'], name='shipping_tr_event_t_f24e4d_idx'),
        ),
    ]
