# Generated by Django 5.2.1 on 2025-08-09 13:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_orderstatushistory_remove_cart_product_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('external_refund_id', models.CharField(blank=True, help_text='ID del reembolso en el gateway externo', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('external_transaction_id', models.CharField(blank=True, help_text='ID de la transacción en el gateway externo', max_length=255, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('charge', 'Cargo'), ('refund', 'Reembolso'), ('chargeback', 'Contracargo'), ('adjustment', 'Ajuste')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del pago en el gateway externo (MercadoPago, PayPal, etc.)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Respuesta completa del gateway de pagos', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto por cuota', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway_config',
            field=models.JSONField(blank=True, help_text='Configuración específica del gateway de pagos', null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='icon',
            field=models.CharField(blank=True, help_text='URL o nombre del ícono', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo para usar este método', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='max_installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo para usar este método', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='min_installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo'), ('mercado_pago', 'MercadoPago'), ('paypal', 'PayPal'), ('crypto', 'Criptomonedas')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Parcialmente Reembolsado')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa de interés en porcentaje', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_payment_id'], name='payments_pa_externa_00130d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_active', 'display_order'], name='payments_pa_is_acti_7bfcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['payment_type'], name='payments_pa_payment_c8697a_idx'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['payment', 'status'], name='payments_pa_payment_2735e7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', 'transaction_type'], name='payments_pa_payment_acaa94_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['external_transaction_id'], name='payments_pa_externa_828606_idx'),
        ),
    ]
