# Generated by Django 5.2.1 on 2025-05-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='offer_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='offer_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
