# Generated by Django 5.2.1 on 2025-08-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productattribute_offer_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attributeoption',
        ),
        migrations.CreateModel(
            name='ProductAttributeOptionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
                ('attributeoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributeoption')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_links', to='products.productattribute')),
            ],
            options={
                'unique_together': {('product_attribute', 'attribute')},
            },
        ),
    ]
