# Generated by Django 5.1.7 on 2025-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(null=True, related_name='products', to='products.variant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='options',
            field=models.ManyToManyField(null=True, to='products.variantoption'),
        ),
    ]
