# Generated by Django 5.1.7 on 2025-03-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_variants_alter_productvariant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(related_name='products', to='products.variant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='options',
            field=models.ManyToManyField(to='products.variantoption'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.variant'),
        ),
    ]
